const courses = [
    {
        id: 2,
        name: 'Cybersecurity Training Program',
        description: 'This DIR-approved course will provide you with key concepts of cybersecurity and common vulnerabilities for schools. Explain best practices against cyber threats and appropriate responses.',
    },
    {
        id: 3,
        name: 'Cybersecurity Training (Spanish Version)',
        description: '(Cybersecurity Training Program / Ciberseguridad Programa de Capacitación) Este curso aprobado por DIR proporciona una visión general de la ciberseguridad, incluida la importancia de la protección de datos, los diferentes tipos de amenazas, así como los efectos de los datos no seguros.'
    },
    {
        id: 10,
        name: 'A Framework for Understanding Poverty 1',
        description: 'Dr. Ruby Payne brings her knowledge and expertise to Eduhero with a three-part course series, A Framework for Understanding Poverty. Part I focuses on developing your understanding of class differences and poverty in terms of resources and rules.'
    },
    {
        id: 11,
        name: 'A Framework for Understanding Poverty 2',
        description: 'Part II of the course series focuses on Teaching Actions 1 - 4. These actions are related to developing mutual respect, teaching hidden rules, knowing home resources, and teaching the formal register. (Updated Feb 2023)'
    },
    {
        id: 12,
        name: 'A Framework for Understanding Poverty 3',
        description: 'In Part III, you will focus on Teaching Actions 5 - 10: using mental models, teaching abstract processes, the importance of planning, using the adult voice and reframing, understanding family resources and dynamics, and teaching students to ask questions.'
    },

    {
		"id" : 16,
		"course_name" : "GT: Differentiating Instruction for GT Students",
		"course_desc" : "This course aims to help you clearly understand what Differentiated Instruction for G/T is—and isn’t—and the four key ways to differentiate: content, process, product, and learning environment.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 2180,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 1,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2017-07-01"
	},
	{
		"id" : 17,
		"course_name" : "GT: Emotional Needs of GT Students",
		"course_desc" : "Better understand the emotional characteristics of gifted students, apply strategies to support their emotional needs, and evaluate your role in upholding the Gifted Student’s Bill of Rights.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 2180,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2017-07-28"
	},
	{
		"id" : 18,
		"course_name" : "GT: Growth & Maturity in GT Students",
		"course_desc" : "This course explores the link between G/T students’ intellectual and social development and the teaching of teamwork and creativity. You'll learn to build teamwork skills through experiential and problem-based learning and discover extracurricular team competition opportunities.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 2180,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2017-07-28"
	},
	{
		"id" : 19,
		"course_name" : "GT: Engaging the Gifted Student",
		"course_desc" : "The purpose of this Gifted and Talented course is to replace some of the myths and misconceptions about our GT population with learning environments and teaching strategies that engage, motivate, and challenge them.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 2180,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2017-08-01"
	},
	{
		"id" : 20,
		"course_name" : "GT: The Twice Exceptional Student",
		"course_desc" : "This course covers key rules and regulations for twice-exceptional (2E) learners, helps you recognize their cognitive and emotional traits, and provides downloadable resources for your GT professional development portfolio.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 1,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2017-08-01"
	},
	{
		"id" : 21,
		"course_name" : "GT: Raising the Bar",
		"course_desc" : "This course provides specific tools and techniques to raise the bar so Gifted and Talented students are challenged and are learning new material daily in school.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1153,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 1,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 26 | 40 | 60 | 105 | ",
		"date_created" : "2017-07-25"
	},
	{
		"id" : 22,
		"course_name" : "GT: Increasing Your GT Diversity",
		"course_desc" : "In this Gifted and Talented course, we cover Gardner's Multiple Intelligences and the Renzulli Giftedness model, as well as strategies for supporting diverse students.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 1,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 26 | 40 | 60 | 105 | ",
		"date_created" : "2017-07-13"
	},
	{
		"id" : 23,
		"course_name" : "GT: Working with GT Parents",
		"course_desc" : "Learn how to understand concerns and communicate effectively with parents/guardians of GT students. You will also go over strategies and options for GT students and brainstorm possible scenarios.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 1,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 26 | 72 | 105 | ",
		"date_created" : "2017-10-24"
	},
	{
		"id" : 24,
		"course_name" : "GT: Overcoming Roadblocks to GT Success",
		"course_desc" : "This Gifted and Talented course features innovative instructional strategies teachers can use to navigate around roadblocks and empower gifted students to reach their learning potential.  ",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 51 | 105 | ",
		"date_created" : "2018-05-08"
	},
	{
		"id" : 25,
		"course_name" : "GT: Tech Tools for the GT Student",
		"course_desc" : "In this GT course, explore tips and tricks for customizing the GT experience for your students using Google Slides, HyperDocs, and more!",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 398,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 32 | 40 | 55 | 105 | ",
		"date_created" : "2018-10-09"
	},
	{
		"id" : 26,
		"course_name" : "GT: Differentiated Assessments",
		"course_desc" : "Learn key assessment terms, understand the need for differentiated assessments for GT students, explore five assessment tools, and apply them to NAGC Assessment Standard 2.<br><br>",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 2180,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2018-11-29"
	},
	{
		"id" : 27,
		"course_name" : "GT: Energizing K-5 GT Science",
		"course_desc" : "This course aims to help you understand the four levels of inquiry-based science teaching, adapt them for gifted learners, consider key implementation factors, and apply your learning through a Science Carnival demonstration.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 367,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 78 | 82 | 83 | 105 | ",
		"date_created" : "2019-03-06"
	},
	{
		"id" : 28,
		"course_name" : "GT Instruction in the ELAR Classroom",
		"course_desc" : "Shakespeare Sits Here: GT Instruction in the ELAR classroom provides real-world examples of how to consistently challenge and inspire Gifted and Talented students through an established culture of learning.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1153,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 40 | 82 | 86 | 105 | 114 | ",
		"date_created" : "2019-08-27"
	},
	{
		"id" : 29,
		"course_name" : "GT: Personality Typing and GT Students",
		"course_desc" : "This course will introduce you to Myers-Briggs personality typing and patterns in types among adults and GT students. You will become familiar with these types, discover your own, and explore strategies for teaching GT students with different dimension preferences.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1153,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | 114 | ",
		"date_created" : "2020-01-06"
	},
	{
		"id" : 30,
		"course_name" : "GT: Growth Approach to GT Instruction",
		"course_desc" : "Teachers can be flexible and insightful escalator operators, continually challenging and extending the most capable students beyond where they are. This course will showcase effective approaches to GT instruction, how to maximize deeper discussions and how to challenge and inspire passion in students.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1153,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 51 | 105 | 114 | ",
		"date_created" : "2020-10-14"
	},
	{
		"id" : 31,
		"course_name" : "GT: Functional Perfectionism",
		"course_desc" : "This course guides you in assessing your own perfectionism, understanding its types, recognizing patterns in GT students, and coaching both students and parents in healthy perfectionism strategies.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 2180,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 1,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 105 | ",
		"date_created" : "2020-10-20"
	},
	{
		"id" : 32,
		"course_name" : "GT STEM Inquiry using PhET Simulations",
		"course_desc" : "Explore and evaluate PhET simulations, complete an inquiry-based STEM lesson, and assess the sim for compatibility, accessibility, and TEKS alignment.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1989,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 32 | 40 | 55 | 82 | 83 | 87 | 105 | 114 | ",
		"date_created" : "2021-05-24"
	},
	{
		"id" : 33,
		"course_name" : "GT: Stress and Burnout",
		"course_desc" : "The objectives for this course are that you understand how stress can affect your students’ mental health. Recognize early signs of stress and burnout in your students. Investigate how unhealthy coping with stress can lead to depression, burnout, and suicide. And apply healthy stress coping strategies for use by students, teachers, and parents.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 1153,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 40 | 105 | 114 | ",
		"date_created" : "2021-11-11"
	},
	{
		"id" : 34,
		"course_name" : "GT: Cultivating Creativity in GT Students",
		"course_desc" : "This course focuses on fostering creativity in gifted education. It covers defining creativity and its components, understanding the challenges faced by gifted students, and exploring strategies to enhance creative thinking. Participants will learn to incorporate creative problem-solving approaches into their curriculum and create a classroom environment that supports and encourages creativity.",
		"custom_course" : 0,
		"region" : null,
		"district" : null,
		"campus" : null,
		"creator" : 347767,
		"passing_score" : 70,
		"credits" : 1.00,
		"credit_type" : "gt-cpe",
		"content_level" : 99,
		"mobile_compat" : 0,
		"series_course" : 0,
		"series_pos" : 0,
		"hidden_store" : 0,
		"hidden_catalog" : 0,
		"packages" : "| 2 | 13 | ",
		"tags" : "| 59 | 105 | 115 | ",
		"date_created" : "2024-12-13"
	}
];

export default courses;